name: OWASP Dependency Track Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sbom-check-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Dependency Track Check (Frontend)
        uses: Quobis/action-owasp-dependecy-track-check@v1
        with:
          url: ${{ secrets.OWASP_DT_URL }}
          key: ${{ secrets.OWASP_DT_KEY }}
          language: 'nodejs'
          path: 'frontend'

  sbom-check-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Dependency Track Check (Backend)
        uses: Quobis/action-owasp-dependecy-track-check@v1
        with:
          url: ${{ secrets.OWASP_DT_URL }}
          key: ${{ secrets.OWASP_DT_KEY }}
          language: 'python'
          path: 'backend'
